export enum BlockType {
  Paragraph = 'Paragraph',
  H1 = 'H1',
  H2 = 'H2',
  H3 = 'H3',
  H4 = 'H4',
  H5 = 'H5',
  H6 = 'H6',
  BulletList = 'BulletList',
  OrderedList = 'OrderedList',
  Todo = 'Todo',
  Blockquote = 'Blockquote',
  FencedCode = 'FencedCode',
  HorizontalRule = 'HorizontalRule',
  Table = 'Table',
  MathBlock = 'MathBlock',
  Unknown = 'Unknown',
}
