// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentEntry(arg1, arg2) {
  return window['go']['main']['App']['AddRecentEntry'](arg1, arg2);
}

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function ClearRecentEntries() {
  return window['go']['main']['App']['ClearRecentEntries']();
}

export function ClipboardGetText() {
  return window['go']['main']['App']['ClipboardGetText']();
}

export function ClipboardSetText(arg1) {
  return window['go']['main']['App']['ClipboardSetText'](arg1);
}

export function ConfirmDelete(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDelete'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetActiveModelInfo() {
  return window['go']['main']['App']['GetActiveModelInfo']();
}

export function GetDocumentMetas() {
  return window['go']['main']['App']['GetDocumentMetas']();
}

export function GetDocumentRelations() {
  return window['go']['main']['App']['GetDocumentRelations']();
}

export function GetFileServerPort() {
  return window['go']['main']['App']['GetFileServerPort']();
}

export function GetPendingOpenFile() {
  return window['go']['main']['App']['GetPendingOpenFile']();
}

export function GetRootPath() {
  return window['go']['main']['App']['GetRootPath']();
}

export function HandleOpenFile(arg1) {
  return window['go']['main']['App']['HandleOpenFile'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function OpenImageFileDialog() {
  return window['go']['main']['App']['OpenImageFileDialog']();
}

export function ReadDirEntries(arg1) {
  return window['go']['main']['App']['ReadDirEntries'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function ReloadLLM() {
  return window['go']['main']['App']['ReloadLLM']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveFileContent'](arg1, arg2);
}

export function SearchDocs(arg1) {
  return window['go']['main']['App']['SearchDocs'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function SetRootPath(arg1) {
  return window['go']['main']['App']['SetRootPath'](arg1);
}

export function SetWorkspaceRoot(arg1) {
  return window['go']['main']['App']['SetWorkspaceRoot'](arg1);
}

export function StreamChat(arg1) {
  return window['go']['main']['App']['StreamChat'](arg1);
}

export function SyncWorkspace() {
  return window['go']['main']['App']['SyncWorkspace']();
}
