// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Ack(arg1:string):Promise<string>;

export function AddRecentEntry(arg1:string,arg2:boolean):Promise<void>;

export function BuildWorkspace():Promise<string>;

export function Chat(arg1:string):Promise<string>;

export function ChatCreateSession(arg1:string):Promise<string>;

export function ChatDeleteSession(arg1:number):Promise<string>;

export function ChatGetHistory(arg1:number):Promise<string>;

export function ChatListSessions(arg1:string):Promise<string>;

export function ClearRecentEntries():Promise<void>;

export function ClipboardGetText():Promise<string>;

export function ClipboardSetText(arg1:string):Promise<void>;

export function ConfirmDelete(arg1:string,arg2:boolean):Promise<boolean>;

export function DeleteFile(arg1:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetActiveModelInfo():Promise<string>;

export function GetDocumentMetas():Promise<string>;

export function GetDocumentRelations():Promise<string>;

export function GetFileServerPort():Promise<number>;

export function GetPendingOpenFile():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetRootPath():Promise<string>;

export function GitAutoCommit():Promise<string>;

export function GitCheckInit():Promise<boolean>;

export function GitCommit(arg1:string):Promise<string>;

export function GitCommitFiles(arg1:string,arg2:Array<string>):Promise<string>;

export function GitGenerateCommitMessage(arg1:Array<string>):Promise<string>;

export function GitGetRemote():Promise<string>;

export function GitInit(arg1:string):Promise<string>;

export function GitPull():Promise<string>;

export function GitPush():Promise<string>;

export function GitSetRemote(arg1:string):Promise<string>;

export function GitStatus():Promise<string>;

export function HandleOpenFile(arg1:string):Promise<void>;

export function IsFullscreen():Promise<boolean>;

export function LoadConfig():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function OpenImageFileDialog():Promise<string>;

export function ReadDirEntries(arg1:string):Promise<Array<main.FileEntry>>;

export function ReadFileContent(arg1:string):Promise<string>;

export function ReloadLLM():Promise<string>;

export function SaveConfig(arg1:string):Promise<string>;

export function SaveFileContent(arg1:string,arg2:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SearchDocs(arg1:string):Promise<string>;

export function SetLocale(arg1:string):Promise<void>;

export function SetRootPath(arg1:string):Promise<void>;

export function SetWorkspaceRoot(arg1:string):Promise<void>;

export function StreamChat(arg1:string):Promise<string>;

export function StreamChatWithHistory(arg1:string):Promise<string>;

export function WindowClose():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
