// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRecentEntry(arg1:string,arg2:boolean):Promise<void>;

export function ClearRecentEntries():Promise<void>;

export function ClipboardGetText():Promise<string>;

export function ClipboardSetText(arg1:string):Promise<void>;

export function ConfirmDelete(arg1:string,arg2:boolean):Promise<boolean>;

export function DeleteFile(arg1:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetFileServerPort():Promise<number>;

export function GetRootPath():Promise<string>;

export function LoadConfig():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function OpenImageFileDialog():Promise<string>;

export function ReadDirEntries(arg1:string):Promise<Array<main.FileEntry>>;

export function ReadFileContent(arg1:string):Promise<string>;

export function SaveConfig(arg1:string):Promise<string>;

export function SaveFileContent(arg1:string,arg2:string):Promise<string>;

export function SetLocale(arg1:string):Promise<void>;

export function SetRootPath(arg1:string):Promise<void>;

export function SetWorkspaceRoot(arg1:string):Promise<void>;
