// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadConfig():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function ReadDirEntries(arg1:string):Promise<Array<main.FileEntry>>;

export function ReadFileContent(arg1:string):Promise<string>;

export function SaveConfig(arg1:string):Promise<string>;

export function SaveFileContent(arg1:string,arg2:string):Promise<string>;
