// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileServerPort() {
  return window['go']['main']['App']['GetFileServerPort']();
}

export function GetRootPath() {
  return window['go']['main']['App']['GetRootPath']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function OpenImageFileDialog() {
  return window['go']['main']['App']['OpenImageFileDialog']();
}

export function ReadDirEntries(arg1) {
  return window['go']['main']['App']['ReadDirEntries'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveFileContent'](arg1, arg2);
}

export function SetRootPath(arg1) {
  return window['go']['main']['App']['SetRootPath'](arg1);
}

export function SetWorkspaceRoot(arg1) {
  return window['go']['main']['App']['SetWorkspaceRoot'](arg1);
}
